version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile.yaml
    image: tutorial-db
    restart: always
    ports:
      - 3306:3306
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile.yaml
    image: tutorial-php
    restart: always
    ports:
      - 8000:8000